[2024-08-03T17:07:18.586+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:07:17.545998+00:00 [queued]>
[2024-08-03T17:07:18.597+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:07:17.545998+00:00 [queued]>
[2024-08-03T17:07:18.597+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T17:07:18.598+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-08-03T17:07:18.598+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-08-03T17:07:18.618+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_excel_to_oracle> on 2024-08-03 17:07:17.545998+00:00
[2024-08-03T17:07:18.625+0000] {standard_task_runner.py:55} INFO - Started process 1602 to run task
[2024-08-03T17:07:18.628+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'excel_to_oracle_dag', 'load_excel_to_oracle', 'manual__2024-08-03T17:07:17.545998+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_oracle_dag.py', '--cfg-path', '/tmp/tmp82byv6yx']
[2024-08-03T17:07:18.635+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask load_excel_to_oracle
[2024-08-03T17:07:18.701+0000] {task_command.py:376} INFO - Running <TaskInstance: excel_to_oracle_dag.load_excel_to_oracle manual__2024-08-03T17:07:17.545998+00:00 [running]> on host 92fc8587d3bd
[2024-08-03T17:07:18.769+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=excel_to_oracle_dag
AIRFLOW_CTX_TASK_ID=load_excel_to_oracle
AIRFLOW_CTX_EXECUTION_DATE=2024-08-03T17:07:17.545998+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-03T17:07:17.545998+00:00
[2024-08-03T17:07:18.772+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/excel_to_oracle_dag.py", line 44, in load_excel_to_oracle
    connection = cx_Oracle.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=dsn)
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
[2024-08-03T17:07:18.789+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=excel_to_oracle_dag, task_id=load_excel_to_oracle, execution_date=20240803T170717, start_date=20240803T170718, end_date=20240803T170718
[2024-08-03T17:07:18.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task load_excel_to_oracle (DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help; 1602)
[2024-08-03T17:07:18.839+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-08-03T17:07:18.862+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
